version: '3.8'
services:
  payment-api:
    container_name: payment_api
    build:
      context: .
      dockerfile: Dockerfile
    image: payment:latest
    ports:
      - "8082:8082"
    environment:
      DATABASE_CONNECTION_STRING: jdbc:postgresql://postgres:5432/bankdb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_SCHEMA: bank
      LOCALSTACK_URL: http://localstack:4566
      AWS_ACCESS_KEY: faker
      AWS_SECRET_KEY: faker
      AWS_DEFAULT_REGION: us-east-1
    networks:
      - bank_iac_bank_network

networks:
  bank_iac_bank_network:
    external: true